global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'kafka-exporter'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'kafka-jmx-exporter'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['jmxexporter:5556']

  - job_name: 'kafka-lag-exporter'
    static_configs:
      - targets:
          - 'kafka-lag-exporter:9999'

  - job_name: 'kafka-connector-jdbc'
    static_configs:
      - targets: [ 'kconnect:8080' ]

  - job_name: 'postgres-exporter'
    static_configs:
        - targets: ["postgres-exporter:9187"]

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ["host.docker.internal:8089"]
        labels:
          application: "transaction consumer"